# Generated by Django 4.2.6 on 2023-11-06 10:56

from django.db import migrations, models
import mapbox_location_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address',
            field=mapbox_location_field.models.LocationField(map_attrs={'placeholder': 'Haritadan konum seçiniz.'}, null=True, verbose_name='Siparişin Konumu'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Recived', 'Sipariş alındı'), ('Assigned', 'Servise atandı'), ('Transporting', 'Taşımada'), ('Delivered', 'Teslim edildi')], default='Sipariş alındı', max_length=20, null=True),
        ),
    ]
