# Generated by Django 4.2.6 on 2023-11-12 22:42

from django.db import migrations
import mapbox_location_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_product_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='address',
            field=mapbox_location_field.models.LocationField(map_attrs={'center': [38.612523, 27.433493], 'placeholder': 'Haritadan konum seçiniz.'}, null=True, verbose_name='Siparişin Konumu'),
        ),
    ]
